{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.3"},"colab":{"name":"02_05_Errors_Exceptions_Handling.ipynb","provenance":[],"collapsed_sections":[]}},"cells":[{"cell_type":"markdown","metadata":{"id":"uAVrt1Mri5AZ","colab_type":"text"},"source":["# Assignments for \"Errors and Exception Handling \""]},{"cell_type":"markdown","metadata":{"id":"TRVFGzhqi5Ad","colab_type":"text"},"source":["1. Let us define a divisi\n","\n","```\n","# This is formatted as code\n","```\n","\n","on operation inside a function (using `def`) but to get an error, define the denominator as 0. So, type properly except statement."]},{"cell_type":"code","metadata":{"id":"FP2RX3EWi5Af","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1595020307418,"user_tz":-120,"elapsed":569,"user":{"displayName":"Serhat Ömer Rencber","photoUrl":"","userId":"18274035633187812674"}},"outputId":"496e9557-4fcf-4c43-913c-2d3793ad5ddc"},"source":["def Division():\n","  try:\n","    a=1/0\n","    return a\n","  except Exception as e:\n","    print (\"'{}' error occurred! \".format(e))\n","\n","Division()"],"execution_count":21,"outputs":[{"output_type":"stream","text":["'division by zero' error occurred! \n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"I38GRS_-i5Al","colab_type":"text"},"source":["2. It is possible to get multiple errors after the execution of one try block. So, please define an error-exception issue with `NameError`."]},{"cell_type":"code","metadata":{"id":"-rN9Psdui5Am","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"executionInfo":{"status":"ok","timestamp":1595020318576,"user_tz":-120,"elapsed":807,"user":{"displayName":"Serhat Ömer Rencber","photoUrl":"","userId":"18274035633187812674"}},"outputId":"4f7ddbdf-b7a1-48a5-c076-2c8f436d1c2e"},"source":["def func():\n","  try:\n","    print(hello)\n","  except IOError:\n","    print('A problem occured reading a file.')\n","  except NameError:\n","    print('Name Error.')\n","func()\n","    "],"execution_count":22,"outputs":[{"output_type":"stream","text":["Name Error.\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"H_LG0PBxi5As","colab_type":"text"},"source":["3. Please define a function and with this function, generate a `ValueError` exception simply by entering a string instead of numerical value."]},{"cell_type":"code","metadata":{"id":"2rL3k1Dgi5At","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":51},"executionInfo":{"status":"ok","timestamp":1595020326506,"user_tz":-120,"elapsed":3866,"user":{"displayName":"Serhat Ömer Rencber","photoUrl":"","userId":"18274035633187812674"}},"outputId":"46392289-3581-4e4c-8794-9d1f97f763bb"},"source":["def func():\n","  try:\n","    numbers=int(input(\"Enter numbers\"))\n","  \n","  except ValueError:\n","    print('Value Error.')\n","  else:\n","    print(\"Everything is OK\")\n","func()\n","    "],"execution_count":23,"outputs":[{"output_type":"stream","text":["Enter numbersk\n","Value Error.\n"],"name":"stdout"}]}]}